"""Media import tests.

Uses a tiny video generated by FFmpeg at test time (no committed media files).
Tests that need FFmpeg are skipped automatically when it is not installed.
"""

from __future__ import annotations

import subprocess

import pytest

from app.utils.ffmpeg import ffmpeg_available


@pytest.fixture()
def sample_video(tmp_path):
    """Generate a 1-second 320x240 test video with FFmpeg."""
    if not ffmpeg_available():
        pytest.skip("ffmpeg/ffprobe not available")
    out = tmp_path / "sample.mp4"
    cmd = [
        "ffmpeg",
        "-y",
        "-f",
        "lavfi",
        "-i",
        "testsrc=duration=1:size=320x240:rate=10",
        "-pix_fmt",
        "yuv420p",
        str(out),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    assert proc.returncode == 0, proc.stderr
    assert out.exists()
    return out


def _new_project(client, name="Import Test") -> str:
    return client.post("/api/projects", json={"name": name}).json()["id"]


def test_import_copy_mode(client, sample_video):
    pid = _new_project(client)
    resp = client.post(
        f"/api/projects/{pid}/media/import",
        json={"source_path": str(sample_video), "copy": True},
    )
    assert resp.status_code == 201, resp.text
    media = resp.json()
    assert media["storage_kind"] == "copied"
    assert media["relative_path"] is not None
    assert media["original_filename"] == "sample.mp4"
    assert media["width"] == 320
    assert media["height"] == 240
    assert media["duration_seconds"] and media["duration_seconds"] > 0
    assert media["size_bytes"] and media["size_bytes"] > 0

    # Project reflects the import and exposes a thumbnail + summary.
    project = client.get(f"/api/projects/{pid}").json()
    assert project["status"] == "imported"
    assert project["has_thumbnail"] is True
    assert project["media_count"] == 1
    assert project["duration_seconds"] and project["duration_seconds"] > 0

    # Thumbnails are served.
    assert client.get(f"/api/media/{media['id']}/thumbnail").status_code == 200
    assert client.get(f"/api/projects/{pid}/thumbnail").status_code == 200


def test_import_reference_mode_does_not_copy(client, sample_video):
    pid = _new_project(client)
    resp = client.post(
        f"/api/projects/{pid}/media/import",
        json={"source_path": str(sample_video), "copy": False},
    )
    assert resp.status_code == 201, resp.text
    media = resp.json()
    assert media["storage_kind"] == "referenced"
    assert media["relative_path"] is None
    # Original file is untouched and still where the user left it.
    assert sample_video.exists()


def test_import_missing_file_is_400(client):
    pid = _new_project(client)
    resp = client.post(
        f"/api/projects/{pid}/media/import",
        json={"source_path": "/nope/not-here.mp4", "copy": True},
    )
    assert resp.status_code == 400


def test_list_media(client, sample_video):
    pid = _new_project(client)
    client.post(
        f"/api/projects/{pid}/media/import",
        json={"source_path": str(sample_video), "copy": True},
    )
    resp = client.get(f"/api/projects/{pid}/media")
    assert resp.status_code == 200
    assert len(resp.json()) == 1


def test_large_file_requires_confirmation(client, sample_video, monkeypatch):
    """With the limit forced to 0 GB, any file needs explicit confirmation."""
    from app.config import get_settings

    monkeypatch.setenv("MAX_IMPORT_FILE_GB", "0")
    get_settings.cache_clear()

    pid = _new_project(client)
    resp = client.post(
        f"/api/projects/{pid}/media/import",
        json={"source_path": str(sample_video), "copy": True},
    )
    assert resp.status_code == 409

    # Re-send with confirmation to proceed.
    resp = client.post(
        f"/api/projects/{pid}/media/import",
        json={"source_path": str(sample_video), "copy": True, "confirm_large": True},
    )
    assert resp.status_code == 201, resp.text
